import os
import pandas as pd
from dotenv import load_dotenv
from llama_index.core import Settings, VectorStoreIndex, SimpleDirectoryReader, PromptTemplate
from llama_index.llms.openai import OpenAI
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.core.node_parser import (
    SentenceSplitter,
    TokenTextSplitter,
    SentenceWindowNodeParser,
)
from llama_index.core.postprocessor import MetadataReplacementPostProcessor


EVAL_TEMPLATE_STR = (
    "You are given a reference (ground-truth) answer and an answer generated by a model. "
    "Judge whether the model's answer is semantically consistent with, accurate against, and "
    "as complete as the reference answer.\n"
    "Reply with only 'Yes' or 'No'.\n"
    "\n"
    "Reference answer:\n"
    "----------\n"
    "{ground_truth}\n"
    "----------\n"
    "\n"
    "Model-generated answer:\n"
    "----------\n"
    "{generated_answer}\n"
    "----------\n"
)
eval_template = PromptTemplate(template=EVAL_TEMPLATE_STR)

# Set to False to skip the manual redundancy scoring (non-interactive run, recorded as 0)
INTERACTIVE_SCORING = True


def evaluate_splitter(splitter, documents, question, ground_truth, splitter_name, answer_keyword=None):
    """
    Evaluate how different splitters affect retrieval and generation quality.

    Args:
        splitter: The LlamaIndex splitter object used to split the documents.
        documents: The list of documents to process.
        question: The query string used for retrieval.
        ground_truth: The reference answer to the question.
        splitter_name: The splitter's name, used to identify it in the results.
        answer_keyword: The key phrase used to check whether the context contains
            the answer; falls back to the first 15 characters of ground_truth if empty.
    """
    print(f"--- 开始评估: {splitter_name} ---")

    # 1. Split the documents with the given splitter
    nodes = splitter.get_nodes_from_documents(documents)

    # 2. Build the index
    index = VectorStoreIndex(nodes)

    # 3. Create the query engine
    # Handle SentenceWindowNodeParser specially because it needs a post-processor
    if isinstance(splitter, SentenceWindowNodeParser):
        # Note: sentence-window chunking requires a dedicated post-processor
        query_engine = index.as_query_engine(
            similarity_top_k=5,
            node_postprocessors=[
                MetadataReplacementPostProcessor(target_metadata_key="window")
            ],
        )
    else:
        query_engine = index.as_query_engine(similarity_top_k=5)

    # 4. Retrieve the context
    retrieved_nodes = query_engine.retrieve(question)
    retrieved_context = "\n\n".join([node.get_content() for node in retrieved_nodes])

    # 5. Evaluate: does the retrieved context contain the answer?
    # Exact character matching is brittle for English, so use a case-insensitive key phrase
    keyword = answer_keyword if answer_keyword else ground_truth[:15]
    context_contains_answer = "是" if keyword.lower() in retrieved_context.lower() else "否"

    # 6. Evaluate: is the LLM-generated answer accurate and complete?
    response = query_engine.query(question)
    generated_answer = str(response)
    # Use the LLM as a judge to assess the accuracy of the answer
    eval_response = Settings.llm.predict(
        eval_template,
        ground_truth=ground_truth,
        generated_answer=generated_answer,
    )
    answer_is_accurate = "是" if "yes" in eval_response.strip().lower() else "否"

    # 7. Evaluate: context redundancy (manual scoring)
    if INTERACTIVE_SCORING:
        print("\n检索到的上下文：")
        print(retrieved_context)
        redundancy_score = input(
            f"请为【{splitter_name}】的上下文冗余程度打分 (1-5, 1表示最不冗余, 5表示最冗余): "
        )
        while redundancy_score not in ["1", "2", "3", "4", "5"]:
            redundancy_score = input("无效输入。请输入1到5之间的整数: ")
        redundancy_score = int(redundancy_score)
    else:
        redundancy_score = 0

    # 8. Store the results
    # Use a function attribute to accumulate results across multiple calls
    if not hasattr(evaluate_splitter, "results"):
        evaluate_splitter.results = []

    evaluate_splitter.results.append(
        {
            "分割器": splitter_name,
            "上下文包含答案": context_contains_answer,
            "回答准确": answer_is_accurate,
            "上下文冗余度(1-5)": redundancy_score,
            "节点数": len(nodes),
            "生成回答": generated_answer.strip().replace("\n", " ")[:100] + "...",
        }
    )

    print(f"--- 完成评估: {splitter_name} ---\n")


def print_results_table():
    """Print a summary table of all evaluation results."""
    if hasattr(evaluate_splitter, "results") and evaluate_splitter.results:
        print("\n--- 最终评估结果对比 ---")
        df = pd.DataFrame(evaluate_splitter.results)
        print(df.to_markdown(index=False))
    else:
        print("没有可供显示的评估结果。")


def main():
    """Main entry point."""
    # The assignment entry point goes here. You can keep everything in this file or
    # split it into multiple files, but keep the entry point here.
    # Run from the project root with: python -m chunking_research.main
    load_dotenv()
    api_key = os.getenv("OPENAI_API_KEY")
    api_base = os.getenv("OPENAI_API_BASE", "https://api.openai.com/v1")
    print("loaded api key")

    # Use the official OpenAI interface (instead of openai_like)
    # Note: the gpt-5 family are reasoning models that typically only support the
    # default temperature, so we no longer pass temperature explicitly.
    Settings.llm = OpenAI(
        model="gpt-5",
        api_key=api_key,
        api_base=api_base,
    )

    Settings.embed_model = OpenAIEmbedding(
        model="text-embedding-3-small",
        api_key=api_key,
        api_base=api_base,
    )

    # data/ holds three English papers (converted from PDF to .md):
    # FinGPT (finance), RT-2 (robotics), Med-PaLM (medicine)
    documents = SimpleDirectoryReader("data").load_data()

    # Define the question and reference answer; here we use the FinGPT (finance) paper as the example
    question = "What approach does FinGPT take to build financial large language models, and why?"
    ground_truth = (
        "FinGPT is an open-source financial LLM that takes a data-centric approach: it uses "
        "automatic data curation and lightweight low-rank adaptation (LoRA) to fine-tune "
        "existing LLMs cheaply, so the model can be updated frequently for the fast-changing "
        "finance domain."
    )
    # Key phrase used to check whether the context contains the answer (it does appear in the source)
    answer_keyword = "data-centric"

    # ===== 1. Sentence splitting =====
    sentence_splitter = SentenceSplitter(chunk_size=512, chunk_overlap=50)
    evaluate_splitter(sentence_splitter, documents, question, ground_truth, "Sentence(512/50)", answer_keyword)

    # ===== 2. Token splitting =====
    token_splitter = TokenTextSplitter(chunk_size=128, chunk_overlap=4, separator="\n")
    evaluate_splitter(token_splitter, documents, question, ground_truth, "Token(128/4)", answer_keyword)

    # ===== 3. Sentence-window splitting =====
    sentence_window_splitter = SentenceWindowNodeParser.from_defaults(
        window_size=3,
        window_metadata_key="window",
        original_text_metadata_key="original_text",
    )
    evaluate_splitter(sentence_window_splitter, documents, question, ground_truth, "Sentence Window(3)", answer_keyword)

    # Note: these .md files were extracted from PDFs and only have a single H1 title with no
    # multi-level heading structure, so MarkdownNodeParser would treat each whole document as one
    # huge node, exceeding OpenAI embedding's 8192-token limit and erroring out. Hence we do not
    # use Markdown splitting on this flat text.

    # ===== 4. Parameter comparison: different chunk_size / chunk_overlap =====
    # Observe how chunk size and overlap affect "retrieval precision" and "context richness/redundancy"
    for chunk_size, chunk_overlap in [(256, 20), (512, 50), (1024, 100)]:
        sp = SentenceSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
        evaluate_splitter(
            sp, documents, question, ground_truth, f"Sentence({chunk_size}/{chunk_overlap})", answer_keyword
        )

    print_results_table()


if __name__ == "__main__":
    main()
